#A function to get the predictions result in a tidy format.
#' A function to get the predictions result in a tidy format.
#'
#' @param predictions The predictions generated by SVM.
#' @return A tidy dataset from the predictions
#' @examples
#'  tds_retrieve(predictions)
tds_retrieve = function(predictions) {

  #Getting the probabilities slot from SVM.
  predictions <- attr(predictions, "probabilities")

  #Transforming everything into a tidy data frame using gather.
  predictions_data <- as_data_frame(predictions) %>%
    mutate(document = row.names(predictions)) %>%
    gather(label_predicted, probability, -document) %>%
    arrange(document, -probability)

  #We initialize the main probability result (in case we want to filter quickly the preferred choid of the model)
  predictions_data <- predictions_data %>%
    group_by(document) %>%
    mutate(main_label = ifelse(probability == max(probability), TRUE, FALSE)) %>%
    ungroup()

  return(predictions_data)
}
